# Generated by Django 4.2.28 on 2026-03-14 21:51

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(default=users.models.get_default_team, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.team'),
        ),
    ]
