# Generated by Django 4.2.28 on 2026-03-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_userprofile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
