# Generated by Django 4.2.28 on 2026-03-28 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('actions_completed', models.PositiveIntegerField(default=0)),
                ('total_actions', models.PositiveIntegerField(default=1)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('active_users', models.ManyToManyField(blank=True, help_text='Users currently working on this task.', related_name='active_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Users assigned to this task. Leave empty for "everyone on the team".', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.team')),
            ],
        ),
    ]
