# Generated by Django 4.2.28 on 2026-03-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='whole_team',
            field=models.BooleanField(default=False, help_text='If True, this task is visible to everyone on the team.'),
        ),
    ]
