# Generated by Django 4.2.28 on 2026-04-11 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_task_deadline_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.CharField(choices=[('all', 'All Teams'), ('team', 'My Team'), ('specific', 'Specific Team')], default='all', max_length=10)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_sent', to=settings.AUTH_USER_MODEL)),
                ('target_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='users.team')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
