# Generated by Django 4.2.28 on 2026-04-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_task_deadline_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('exec', 'Exec'), ('member', 'Member'), ('admin', 'Admin')], default='member', max_length=10),
        ),
    ]
