# Generated by Django 4.2.28 on 2026-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_team',
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_teams',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='users.team'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('all', 'All Teams'), ('specific', 'Specific Teams')], default='all', max_length=10),
        ),
    ]
