# Generated by Django 4.2.28 on 2026-04-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_avatar'),
        ('users', '0012_announcementread'),
    ]

    operations = [
    ]
