# Generated by Django 4.2.28 on 2026-04-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_0010_userprofile_avatar_0012_announcementread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=1),
        ),
    ]
